name: Package Application - Android

on: 
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Buildozer & Dependencies
      run: |
        sudo apt update && sudo apt install -y python3-pip openjdk-17-jdk build-essential git unzip aidl
        pip install --upgrade pip
        pip install buildozer cython virtualenv 

    - name: Create buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Edit buildozer.spec
      run: |
        sed -i 's|source.include_exts = py,png,jpg,kv,atlas|source.include_exts = py,png,jpg,ico,kv,atlas|' buildozer.spec
        sed -i 's|source.exclude_exts = txt,pyc|source.exclude_exts = txt,pyc,md|' buildozer.spec
        sed -i 's|^source.include_patterns =|source.include_patterns = src/main-android.py, src/assets/images/icon_256x256.ico|' buildozer.spec
        sed -i 's|application_name =.*|application_name = WME Android|' buildozer.spec
        sed -i 's|package.domain =.*|package.domain = com.yourdomain.wme|' buildozer.spec
        sed -i 's|package.name =.*|package.name = wme|' buildozer.spec
        sed -i 's|package.version =.*|package.version = 1.0.0|' buildozer.spec
        sed -i 's|android.icon =.*|android.icon = src/assets/images/icon_256x256.ico|' buildozer.spec

    - name: Build APK using Buildozer
      run: buildozer -v android debug

    - name: Move APK File
      run: mv bin/*.apk wme-Android.apk

    - name: 📁 Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: "wme-android-${{ github.run_number }}"
        path: wme-Android.apk
