name: Package Application - Android

on: 
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Buildozer & Dependencies
      run: |
        sudo apt update && sudo apt install -y python3-pip openjdk-17-jdk build-essential git unzip
        pip install --upgrade pip
        pip install buildozer cython virtualenv
        
    - name: Create and update buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        sed -i 's/^source.include_exts =.*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
        sed -i 's/^requirements =.*/requirements = python3,kivy/' buildozer.spec
        sed -i 's/^android.arch =.*/android.arch = arm64-v8a,armeabi-v7a/' buildozer.spec

    - name: Run build.py
      run: |
        if [ -f build-android.py ]; then
          python build-android.py
        fi

    - name: Build APK with Buildozer
      run: |
        chmod +x ./buildozer
        buildozer -v android debug

    - name: Move file APK
      run: |
        mkdir -p release
        mv bin/*.apk release/wme-Android.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: "wme-android-${{ github.run_number }}"
        path: release/wme-Android.apk
